In [ ]:
#import packages
import pandas as pd         #reads csv file
import numpy as np          #operates numerical operations
from sklearn.model_selection import train_test_split        #classifies data into training and testing sets
from sklearn.feature_extraction.text import CountVectorizer    #converts text data into a format that can be used by the Naive Bayes model
from sklearn.naive_bayes import MultinomialNB                 #TO GET WORD COUNT AND ITS FREQUENCY

In [ ]:
#import data
spam_df = pd.read_csv("/content/spam.csv")

In [ ]:
spam_df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [ ]:
#turn spam/ham into numerical data, creating a new column called 'spam'
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [ ]:
#create train/test split
x_train, x_test, y_train, y_test = train_test_split(spam_df.Message, spam_df.spam, test_size = 0.30)

In [ ]:
#find word count and store data as a matrix
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [ ]:
#converts sparse matrix into a dense numpy array
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#train model
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [ ]:
#pre-test ham
email_ham = ["hey wanna meet up for the game?"]
email_ham_count = cv.transform(email_ham)           #transform method expects an iterable containing text data as list
model.predict(email_ham_count)

array([0])

In [ ]:
#pre-test spam
email_spam = ["reward money click"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [ ]:
#test model
x_test_count = cv.transform(x_test)                 #transforms the text data into a matrix of token counts
model.score(x_test_count,y_test)

0.9863603732950467